// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MOCfnU6dPbpSw5sroh1SKduPNzfDwCw',
    appId: '1:1022499298930:web:6b101b710aa377fb11eceb',
    messagingSenderId: '1022499298930',
    projectId: 'projeto-allerfree',
    authDomain: 'projeto-allerfree.firebaseapp.com',
    storageBucket: 'projeto-allerfree.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMl4FDxLJ7rZPdotz3LIuQwzdu8E7R7As',
    appId: '1:1022499298930:android:a260c97c4360be1511eceb',
    messagingSenderId: '1022499298930',
    projectId: 'projeto-allerfree',
    storageBucket: 'projeto-allerfree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5OB38kwpeT2Ft2ZqXRitVIdBaemA0qKw',
    appId: '1:1022499298930:ios:b249ecf7014bd2e411eceb',
    messagingSenderId: '1022499298930',
    projectId: 'projeto-allerfree',
    storageBucket: 'projeto-allerfree.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinalAllerfree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OB38kwpeT2Ft2ZqXRitVIdBaemA0qKw',
    appId: '1:1022499298930:ios:b249ecf7014bd2e411eceb',
    messagingSenderId: '1022499298930',
    projectId: 'projeto-allerfree',
    storageBucket: 'projeto-allerfree.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinalAllerfree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_MOCfnU6dPbpSw5sroh1SKduPNzfDwCw',
    appId: '1:1022499298930:web:fe0a3e4fc33e4a9a11eceb',
    messagingSenderId: '1022499298930',
    projectId: 'projeto-allerfree',
    authDomain: 'projeto-allerfree.firebaseapp.com',
    storageBucket: 'projeto-allerfree.firebasestorage.app',
  );
}
